import pandas as pd
import pymysql
from datetime import datetime
import matplotlib.pyplot as plt

#connection to my SQL database
connection = pymysql.connect (
    host='localhost',
    user='root',
    password='stephen0111301468',
    database='enterprise_crm_db',
    cursorclass = pymysql.cursors.DictCursor
)
print("Database connection successful !")

#creating the cursor using my active connection
cursor = connection.cursor()

# calculating customer metrics (frequency and total spend)
query = """
SELECT
c.customer_id,
c.company_name,
COUNT(d.deal_id) AS total_deals,
SUM(d.deal_value) AS total_spent
FROM customers c
JOIN deals d ON c.customer_id = d.customer_id
GROUP BY c.customer_id,c.company_name;
"""
cursor.execute(query)
crm_data = cursor.fetchall()

# convert the multiple table results into a pandas dataframe
df_crm = pd.DataFrame(crm_data)

#calculating average order value AOV using pandas column math
df_crm['avg_order_value'] = df_crm['total_spent'] / df_crm['total_deals']

print("\nHere is your Enhanced CRM Analytics DataFrame:")
print(df_crm)

#generating a unique timestamp filename
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
report_filename = f"crm_customer_report_{timestamp}.csv"

#export the dataframe directly into a CSV report file
df_crm.to_csv('crm_customer_report.csv',index=False)
print("\nSuccess ! Report saved as 'crm_customer_report.csv' in your Downloads folder.")

#generating and saving a bar chart visualization
plt.figure(figsize=(10, 5))
plt.bar(df_crm['company_name'], df_crm['total_spent'], color='royalblue')
plt.title('Total Revenue Generated by Customer')
plt.xlabel('Company Name')
plt.ylabel('Total Spend')
plt.xticks(rotation=15)
plt.tight_layout()

# Save the chart as a timestamped image file
chart_filename = f'crm_spend_chart_{timestamp}.png'
plt.savefig(chart_filename)
print(f"Success! Chart saved as '{chart_filename}' in your Downloads folder.")


cursor.close()
connection.close()

